import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useAppSelector } from '@/lib/redux/hooks';
import Modal from '@/components/Modal';

export default function Home() {
  const mode = useAppSelector(state => state.mode.darkMode);
  return (
    <>
      <Head>
        <title>MY LIBRARY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          hello
          {/* <Modal /> */}
      </main>
    </>
  )
}
